version: '2.4'

services:
  mysql:
    image: mysql:8
    ports:
      - "3306:3306"
    volumes:
      - ./resources/mysql_data.sql:/docker-entrypoint-initdb.d/00_init.sql
      - ates-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=admin
      - MYSQL_USER=admin
volumes:
  ates-db: